[package]
name = "loadersheet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.3", features = ["all-widgets", "termion"], default-features = false }
termion = "4.0.0"
